//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Children
    {
        public int id { get; set; }
        public System.DateTime birthDate { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int parentID { get; set; }
        public int married { get; set; }
    
        public virtual ToraMen ToraMen { get; set; }
    }
}
