//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loans
    {
        public System.DateTime date { get; set; }
        public int lenderID { get; set; }
        public int borrowerID { get; set; }
        public int takeOrBack { get; set; }
        public string firstNameLender { get; set; }
        public string lastNameLender { get; set; }
        public string firstNameBorrower { get; set; }
        public string lastNameBorrower { get; set; }
        public string wayOfReturn { get; set; }
        public Nullable<int> accountNumberLender { get; set; }
        public Nullable<int> accountNumberBorrower { get; set; }
    
        public virtual BankAccounts BankAccounts { get; set; }
        public virtual BankAccounts BankAccounts1 { get; set; }
    }
}
