//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scholarships
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int basic { get; set; }
        public int Musar { get; set; }
        public int dailyRoutine { get; set; }
        public int continuous { get; set; }
        public Nullable<int> lastMonthMark { get; set; }
        public Nullable<int> excellenceScholarship { get; set; }
        public Nullable<int> holidayScholarship { get; set; }
        public Nullable<int> religiousMinistry { get; set; }
        public int Scholarships1 { get; set; }
        public int ScholarshipsAndLoan { get; set; }
        public int refund { get; set; }
        public Nullable<int> donation { get; set; }
        public int remainderDebt { get; set; }
    }
}
